In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Pandas is used for data analysis

In [4]:
#Series and Dataframes
#Series : 1D (column)
#DataFrame : 2D (rows and columns)
#DataFrame could be considered as an excel spreadsheet structure

In [5]:
#Series: similar to a 1D numpy array, but there are a few differences
#Series can have a customized labeled index
#If there is any value missing in a series, it will be displayed as NaN
#But in numpy, the missing value is ignored and not displayed at all

In [7]:
a=np.array([2,4,6,8,4])
a

array([2, 4, 6, 8, 4])

In [8]:
type(a)

numpy.ndarray

In [9]:
a.ndim

1

In [10]:
a[0]

2

In [12]:
s=pd.Series(a)
s

0    2
1    4
2    6
3    8
4    4
dtype: int32

In [13]:
type(s)

pandas.core.series.Series

In [15]:
s[3]

8

In [16]:
list1=[10,30,23,45,67]
s1=pd.Series(list1)
s1

0    10
1    30
2    23
3    45
4    67
dtype: int64

In [17]:
#create a series with a fancy index
list1=[10,30,23,45,67]
labels=['v','w','x','y','z']
s2=pd.Series(list1,index=labels)
s2

v    10
w    30
x    23
y    45
z    67
dtype: int64

In [36]:
type(s2)

pandas.core.series.Series

In [18]:
s2['w']

30

In [19]:
s2['x']

23

In [20]:
#Task
#Create an array for marks of a student for 5 different subjects
#Create a list containing the 5 subject names
#Create a pandas Series with marks as values, and subjectnames as index

In [21]:
marks=np.array([34,45,49,38,46])
sub_names=['English','Sociology','Computers','Sports','History']
mark_subject=pd.Series(marks, index=sub_names)
mark_subject

English      34
Sociology    45
Computers    49
Sports       38
History      46
dtype: int32

In [22]:
marks2=np.random.randint(30,50,5)
marks2

array([37, 49, 41, 37, 33])

In [23]:
mark_subject=pd.Series(marks2, index=sub_names)
mark_subject

English      37
Sociology    49
Computers    41
Sports       37
History      33
dtype: int32

In [24]:
d={'a':2,'b':4,'c':3}

In [26]:
type(d)

dict

In [30]:
pd.Series(d)

a    2
b    4
c    3
dtype: int64

In [31]:
pd.Series(d,index=['a','b','c','d','e'])

a    2.0
b    4.0
c    3.0
d    NaN
e    NaN
dtype: float64

In [29]:
pd.Series(d,index=['c','d','e'])

c    3.0
d    NaN
e    NaN
dtype: float64

In [27]:
#DataFrames

In [39]:
mydataset={'cars':['BMW','Volvo','Fiat'],'values':[3,7,2]}

In [40]:
type(mydataset)

dict

In [41]:
d2=pd.DataFrame(mydataset)
d2

cars  values
0    BMW       3
1  Volvo       7
2   Fiat       2

In [35]:
type(d2)

pandas.core.frame.DataFrame

In [53]:
marks=np.random.randint(20,50,16)
marks

array([28, 44, 33, 39, 35, 30, 45, 28, 27, 23, 26, 41, 37, 45, 23, 24])

In [56]:
np.random.seed(1)
marks=np.random.randint(20,50,(4,4))
marks

array([[25, 31, 32, 28],
       [29, 31, 25, 35],
       [20, 36, 21, 32],
       [27, 33, 48, 26]])

In [45]:
marks.ndim

2

In [46]:
marks.shape

(4, 4)

In [47]:
Subjects=['Math','Computers','Biology','Sports']
Students=['Peter','Josh','Rob','John']

In [59]:
df=pd.DataFrame(marks,columns=Subjects,index=Students)
df

Math  Computers  Biology  Sports
Peter    25         31       32      28
Josh     29         31       25      35
Rob      20         36       21      32
John     27         33       48      26

In [60]:
df['Math']

Peter    25
Josh     29
Rob      20
John     27
Name: Math, dtype: int32

In [61]:
df['Sports']

Peter    28
Josh     35
Rob      32
John     26
Name: Sports, dtype: int32

In [64]:
df['Total']=df['Math']+df['Computers']+df['Biology']+df['Sports']
df['Total']

Peter    116
Josh     120
Rob      109
John     134
Name: Total, dtype: int32

In [65]:
df

Math  Computers  Biology  Sports  Total
Peter    25         31       32      28    116
Josh     29         31       25      35    120
Rob      20         36       21      32    109
John     27         33       48      26    134

In [66]:
df['Percentage']=(df['Total']/200)*100
df

Math  Computers  Biology  Sports  Total  Percentage
Peter    25         31       32      28    116        58.0
Josh     29         31       25      35    120        60.0
Rob      20         36       21      32    109        54.5
John     27         33       48      26    134        67.0