In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Pandas is used for data analysis

In [3]:
#Series and Dataframes
#Series : 1D (column)
#DataFrame : 2D (rows and columns)
#DataFrame could be considered as an excel spreadsheet structure

In [4]:
#Series: similar to a 1D numpy array, but there are a few differences
#Series can have a customized labeled index
#If there is any value missing in a series, it will be displayed as NaN
#But in numpy, the missing value is ignored and not displayed at all

In [5]:
a=np.array([2,4,6,8,4])
a

array([2, 4, 6, 8, 4])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.ndim

1

In [8]:
a[0]

2

In [9]:
s=pd.Series(a)
s

0    2
1    4
2    6
3    8
4    4
dtype: int32

In [10]:
type(s)

pandas.core.series.Series

In [11]:
s[3]

8

In [12]:
list1=[10,30,23,45,67]
s1=pd.Series(list1)
s1

0    10
1    30
2    23
3    45
4    67
dtype: int64

In [13]:
#create a series with a fancy index
list1=[10,30,23,45,67]
labels=['v','w','x','y','z']
s2=pd.Series(list1,index=labels)
s2

v    10
w    30
x    23
y    45
z    67
dtype: int64

In [14]:
type(s2)

pandas.core.series.Series

In [15]:
s2['w']

30

In [16]:
s2['x']

23

In [17]:
#Task
#Create an array for marks of a student for 5 different subjects
#Create a list containing the 5 subject names
#Create a pandas Series with marks as values, and subjectnames as index

In [18]:
marks=np.array([34,45,49,38,46])
sub_names=['English','Sociology','Computers','Sports','History']
mark_subject=pd.Series(marks, index=sub_names)
mark_subject

English      34
Sociology    45
Computers    49
Sports       38
History      46
dtype: int32

In [19]:
marks2=np.random.randint(30,50,5)
marks2

array([43, 43, 36, 46, 39])

In [20]:
mark_subject=pd.Series(marks2, index=sub_names)
mark_subject

English      43
Sociology    43
Computers    36
Sports       46
History      39
dtype: int32

In [21]:
d={'a':2,'b':4,'c':3}

In [22]:
type(d)

dict

In [23]:
pd.Series(d)

a    2
b    4
c    3
dtype: int64

In [24]:
pd.Series(d,index=['a','b','c','d','e'])

a    2.0
b    4.0
c    3.0
d    NaN
e    NaN
dtype: float64

In [25]:
pd.Series(d,index=['c','d','e'])

c    3.0
d    NaN
e    NaN
dtype: float64

In [26]:
#DataFrames

In [27]:
mydataset={'cars':['BMW','Volvo','Fiat'],'values':[3,7,2]}

In [28]:
type(mydataset)

dict

In [29]:
d2=pd.DataFrame(mydataset)
d2

cars  values
0    BMW       3
1  Volvo       7
2   Fiat       2

In [30]:
type(d2)

pandas.core.frame.DataFrame

In [31]:
marks=np.random.randint(20,50,16)
marks

array([23, 23, 38, 28, 23, 25, 49, 38, 21, 26, 31, 29, 34, 42, 27, 33])

In [32]:
np.random.seed(1)
marks=np.random.randint(20,50,(4,4))
marks

array([[25, 31, 32, 28],
       [29, 31, 25, 35],
       [20, 36, 21, 32],
       [27, 33, 48, 26]])

In [33]:
marks.ndim

2

In [34]:
marks.shape

(4, 4)

In [35]:
Subjects=['Math','Computers','Biology','Sports']
Students=['Peter','Josh','Rob','John']

In [36]:
df=pd.DataFrame(marks,columns=Subjects,index=Students)
df

Math  Computers  Biology  Sports
Peter    25         31       32      28
Josh     29         31       25      35
Rob      20         36       21      32
John     27         33       48      26

In [37]:
df['Math']

Peter    25
Josh     29
Rob      20
John     27
Name: Math, dtype: int32

In [38]:
df['Sports']

Peter    28
Josh     35
Rob      32
John     26
Name: Sports, dtype: int32

In [39]:
df['Total']=df['Math']+df['Computers']+df['Biology']+df['Sports']
df['Total']

Peter    116
Josh     120
Rob      109
John     134
Name: Total, dtype: int32

In [40]:
df

Math  Computers  Biology  Sports  Total
Peter    25         31       32      28    116
Josh     29         31       25      35    120
Rob      20         36       21      32    109
John     27         33       48      26    134

In [41]:
df['Percentage']=(df['Total']/200)*100
df

Math  Computers  Biology  Sports  Total  Percentage
Peter    25         31       32      28    116        58.0
Josh     29         31       25      35    120        60.0
Rob      20         36       21      32    109        54.5
John     27         33       48      26    134        67.0

In [42]:
df.sum()

Math          101.0
Computers     131.0
Biology       126.0
Sports        121.0
Total         479.0
Percentage    239.5
dtype: float64

In [45]:
df=df.drop('Percentage',axis=1)

In [47]:
df=df.drop('Total',axis=1)
df

Math  Computers  Biology  Sports
Peter    25         31       32      28
Josh     29         31       25      35
Rob      20         36       21      32
John     27         33       48      26

In [48]:
df.drop('Rob',axis=0)

Math  Computers  Biology  Sports
Peter    25         31       32      28
Josh     29         31       25      35
John     27         33       48      26

In [49]:
df

Math  Computers  Biology  Sports
Peter    25         31       32      28
Josh     29         31       25      35
Rob      20         36       21      32
John     27         33       48      26

In [50]:
df.sum(axis=0)

Math         101
Computers    131
Biology      126
Sports       121
dtype: int64

In [51]:
df.sum(axis=1)

Peter    116
Josh     120
Rob      109
John     134
dtype: int64

In [52]:
d={'Cricket':[1,3,np.nan,4,6,7,2,np.nan],
  'Baseball':[5,np.nan,np.nan,5,7,4,7,3],
  'Tennis':[1,2,3,4,5,6,7,8]}

In [53]:
df=pd.DataFrame(d)
df

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      3.0       NaN       2
2      NaN       NaN       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7
7      NaN       3.0       8

In [55]:
#Null values or missing values
#Remove the columns or rows containing the null values
#Fill the missing values with 0
#Fill the missing values with values of mean/median/mode of the respective columns

In [56]:
df.dropna(axis=0) #dropping the rows containing null values

Cricket  Baseball  Tennis
0      1.0       5.0       1
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7

In [57]:
df.dropna(axis=1) #dropping the columns containing null values

Tennis
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8

In [59]:
df.fillna(value=0)

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      3.0       0.0       2
2      0.0       0.0       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7
7      0.0       3.0       8

In [60]:
df

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      3.0       NaN       2
2      NaN       NaN       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7
7      NaN       3.0       8

In [63]:
#df.fillna(value=0)
df['Cricket']=df['Cricket'].fillna(value=df['Cricket'].mean())
df

Cricket  Baseball  Tennis
0  1.000000       5.0       1
1  3.000000       NaN       2
2  3.833333       NaN       3
3  4.000000       5.0       4
4  6.000000       7.0       5
5  7.000000       4.0       6
6  2.000000       7.0       7
7  3.833333       3.0       8

In [61]:
df['Cricket'].mean()

3.8333333333333335

In [64]:
df['Baseball']=df['Baseball'].fillna(value=df['Baseball'].median())
df

Cricket  Baseball  Tennis
0  1.000000       5.0       1
1  3.000000       5.0       2
2  3.833333       5.0       3
3  4.000000       5.0       4
4  6.000000       7.0       5
5  7.000000       4.0       6
6  2.000000       7.0       7
7  3.833333       3.0       8

In [65]:
df['Baseball'].mode()

0    5.0
dtype: float64

In [68]:
df['Baseball'].mode().values

array([5.])

In [69]:
df['Baseball'].mode().values[0]

5.0

In [66]:
df['Baseball'].median()

5.0

In [67]:
df['Baseball'].mean()

5.125