In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#https://www.kaggle.com/datasets/anthonypino/melbourne-housing-market?select=Melbourne_housing_FULL.csv
df=pd.read_csv("Melbourne_housing_FULL.csv")
df.head()

Suburb             Address  Rooms Type      Price Method SellerG  \
0  Abbotsford       68 Studley St      2    h        NaN     SS  Jellis   
1  Abbotsford        85 Turner St      2    h  1480000.0      S  Biggin   
2  Abbotsford     25 Bloomburg St      2    h  1035000.0      S  Biggin   
3  Abbotsford  18/659 Victoria St      3    u        NaN     VB  Rounds   
4  Abbotsford        5 Charles St      3    h  1465000.0     SP  Biggin   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/09/2016       2.5    3067.0  ...       1.0  1.0     126.0           NaN   
1  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
2  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
3  4/02/2016       2.5    3067.0  ...       2.0  1.0       0.0           NaN   
4  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   

   YearBuilt         CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN  Yarra City Council  -37.8014    144.9958  Northern Metropolitan   
1        NaN  Yarra City Council  -37.7996    144.9984  Northern Metropolitan   
2     1900.0  Yarra City Council  -37.8079    144.9934  Northern Metropolitan   
3        NaN  Yarra City Council  -37.8114    145.0116  Northern Metropolitan   
4     1900.0  Yarra City Council  -37.8093    144.9944  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [3]:
df.shape

(34857, 21)

In [4]:
df.sample(5)

Suburb           Address  Rooms Type      Price Method  \
15234        Preston     49 Wallace St      3    h   990000.0      S   
15075            Kew   3/234 Cotham Rd      2    u   630000.0      S   
29371     Cheltenham     2C Gilford Gr      2    t   955000.0      S   
21763       Carnegie  2/43 Margaret St      3    u  1077000.0      S   
29931  Taylors Lakes     10 Warrego Pl      4    h   770000.0     PI   

             SellerG        Date  Distance  Postcode  ...  Bathroom  Car  \
15234  hockingstuart   3/06/2017       8.4    3072.0  ...       1.0  1.0   
15075      Lindellas   3/06/2017       5.4    3101.0  ...       1.0  1.0   
29371         Buxton   6/01/2018      17.9    3192.0  ...       1.0  1.0   
21763       Woodards  19/08/2017      10.1    3163.0  ...       2.0  2.0   
29931            YPA   6/01/2018      15.5    3038.0  ...       2.0  2.0   

       Landsize  BuildingArea  YearBuilt              CouncilArea Lattitude  \
15234     545.0           NaN        NaN     Darebin City Council -37.74258   
15075    1037.0           NaN     1960.0  Boroondara City Council -37.80897   
29371       NaN         117.0     2002.0     Bayside City Council -37.96273   
21763       NaN           NaN        NaN   Glen Eira City Council -37.89344   
29931     820.0           NaN        NaN    Brimbank City Council -37.68991   

       Longtitude             Regionname Propertycount  
15234   144.99309  Northern Metropolitan       14577.0  
15075   145.04759  Southern Metropolitan       10331.0  
29371   145.04935  Southern Metropolitan        9758.0  
21763   145.06265  Southern Metropolitan        7822.0  
29931   144.78194   Western Metropolitan        5336.0  

[5 rows x 21 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Suburb         34857 non-null  object 
 1   Address        34857 non-null  object 
 2   Rooms          34857 non-null  int64  
 3   Type           34857 non-null  object 
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object 
 6   SellerG        34857 non-null  object 
 7   Date           34857 non-null  object 
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object 
 17  Lattitude      26881 non-null  float64
 18  Longti

In [6]:
df.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [7]:
#separate the numerical and non-numerical column names
df.dtypes # this prints a series depicting the datatypes of each column

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [8]:
df.dtypes[df.dtypes=='object']

Suburb         object
Address        object
Type           object
Method         object
SellerG        object
Date           object
CouncilArea    object
Regionname     object
dtype: object

In [9]:
df.dtypes[df.dtypes!='object']

Rooms              int64
Price            float64
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
Lattitude        float64
Longtitude       float64
Propertycount    float64
dtype: object

In [10]:
df.dtypes[df.dtypes!='object'].index

Index(['Rooms', 'Price', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude', 'Longtitude',
       'Propertycount'],
      dtype='object')

In [11]:
num_col=df.dtypes[df.dtypes!='object'].index.values
num_col

array(['Rooms', 'Price', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom',
       'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude',
       'Longtitude', 'Propertycount'], dtype=object)

In [12]:
cat_col=df.dtypes[df.dtypes=='object'].index.values
cat_col

array(['Suburb', 'Address', 'Type', 'Method', 'SellerG', 'Date',
       'CouncilArea', 'Regionname'], dtype=object)

In [13]:
#Curse of dimensionality
#Only the nest features needs to be selected

In [14]:
df.nunique()

Suburb             351
Address          34009
Rooms               12
Type                 3
Price             2871
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [15]:
#We will remove the categorical columns which have more than 30 unique values

In [16]:
for col in cat_col:
    if (df[col].nunique()>30):
        df=df.drop(col,axis=1)

In [17]:
df.shape

(34857, 16)

In [20]:
df.sample(5)

Rooms Type      Price Method  Distance  Postcode  Bedroom2  Bathroom  \
31728      3    u   818000.0      S       7.5    3040.0       3.0       1.0   
32895      4    h  1240000.0      S      15.5    3106.0       NaN       NaN   
9101       3    h  1200000.0      S       6.6    3011.0       2.0       1.0   
19280      3    u   537000.0      S      39.0    3807.0       3.0       1.0   
27647      5    h  1495000.0      S      17.9    3192.0       5.0       2.0   

       Car  Landsize  BuildingArea  YearBuilt  Lattitude  Longtitude  \
31728  1.0     233.0           NaN     1990.0  -37.75412   144.89546   
32895  NaN       NaN           NaN        NaN        NaN         NaN   
9101   1.0     374.0           NaN        NaN  -37.80570   144.88820   
19280  1.0     460.0           NaN        NaN  -38.04668   145.36939   
27647  3.0     557.0         166.0     1950.0  -37.96950   145.05930   

                  Regionname  Propertycount  
31728   Western Metropolitan         9264.0  
32895   Eastern Metropolitan         6202.0  
9101    Western Metropolitan         2417.0  
19280       Eastern Victoria         2332.0  
27647  Southern Metropolitan         9758.0

In [21]:
df[['Rooms','Bedroom2']]

Rooms  Bedroom2
0          2       2.0
1          2       2.0
2          2       2.0
3          3       3.0
4          3       3.0
...      ...       ...
34852      4       4.0
34853      2       2.0
34854      2       2.0
34855      3       NaN
34856      2       2.0

[34857 rows x 2 columns]

In [22]:
df=df.drop(columns=['Bedroom2','Postcode','Lattitude','Longtitude'])
df.shape

(34857, 12)

In [28]:
df.sample(10)

Rooms Type      Price Method  Distance  Bathroom  Car  Landsize  \
34578      3    h  1300000.0     PI       5.3       NaN  NaN       NaN   
7924       3    h  2100000.0      S       3.8       2.0  1.0     170.0   
30236      4    h   556000.0     PI      20.6       2.0  2.0       NaN   
6064       5    h        NaN     PN       5.6       4.0  5.0     659.0   
12270      3    t  1050000.0      S      13.9       NaN  NaN       NaN   
14023      1    u   385000.0      S       8.5       1.0  1.0    1851.0   
25584      3    h  1700000.0      S      13.8       1.0  2.0     649.0   
26346      2    h   935000.0     SA       8.4       1.0  1.0       NaN   
11359      3    h        NaN      S       7.5       1.0  1.0     249.0   
21570      4    h  1260000.0     PI      12.4       2.0  2.0       NaN   

       BuildingArea  YearBuilt             Regionname  Propertycount  
34578           NaN        NaN  Northern Metropolitan        11364.0  
7924            NaN        NaN  Southern Metropolitan         8648.0  
30236         158.0     2010.0  Northern Metropolitan        15510.0  
6064          418.0     2014.0  Southern Metropolitan        10331.0  
12270           NaN        NaN  Southern Metropolitan        10969.0  
14023           NaN        NaN  Southern Metropolitan         4898.0  
25584           NaN        NaN  Southern Metropolitan        10969.0  
26346           NaN        NaN  Northern Metropolitan        14577.0  
11359         120.0     1910.0  Southern Metropolitan         6482.0  
21570           NaN        NaN   Eastern Metropolitan         5420.0

In [29]:
df['Landsize']=df['Landsize'].fillna(df['Landsize'].mean())
df['BuildingArea']=df['BuildingArea'].fillna(df['BuildingArea'].mean())

In [33]:
df.isnull().sum()

Rooms                0
Type                 0
Price             7610
Method               0
Distance             1
Bathroom          8226
Car               8728
Landsize             0
BuildingArea         0
YearBuilt        19306
Regionname           3
Propertycount        3
dtype: int64

In [42]:
df['BuildingArea'].mode().values[0]

160.2564003565711

In [37]:
df['Regionname'].mode().values[0]

'Southern Metropolitan'

In [43]:
df['Bathroom']=df['Bathroom'].fillna(df['Bathroom'].mode().values[0])
df['Car']=df['Car'].fillna(df['Car'].mode().values[0])
df['Propertycount']=df['Propertycount'].fillna(df['Propertycount'].mode().values[0])
df['Regionname']=df['Regionname'].fillna(df['Regionname'].mode().values[0])
df['Distance']=df['Distance'].fillna(df['Distance'].mode().values[0])

In [44]:
df.isnull().sum()

Rooms                0
Type                 0
Price             7610
Method               0
Distance             0
Bathroom             0
Car                  0
Landsize             0
BuildingArea         0
YearBuilt        19306
Regionname           0
Propertycount        0
dtype: int64

In [45]:
df['YearBuilt']

0           NaN
1           NaN
2        1900.0
3           NaN
4        1900.0
          ...  
34852       NaN
34853    2018.0
34854    2000.0
34855       NaN
34856    1930.0
Name: YearBuilt, Length: 34857, dtype: float64

In [46]:
df['YearBuilt']=2021-df['YearBuilt']

In [49]:
df['YearBuilt']=df['YearBuilt'].fillna(df['YearBuilt'].mode().values[0])

In [50]:
df['Price']=df['Price'].fillna(df['Price'].mean())

In [51]:
df.isnull().sum()

Rooms            0
Type             0
Price            0
Method           0
Distance         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
Regionname       0
Propertycount    0
dtype: int64

In [52]:
df.head(2)

Rooms Type         Price Method  Distance  Bathroom  Car  Landsize  \
0      2    h  1.050173e+06     SS       2.5       1.0  1.0     126.0   
1      2    h  1.480000e+06      S       2.5       1.0  1.0     202.0   

   BuildingArea  YearBuilt             Regionname  Propertycount  
0      160.2564       51.0  Northern Metropolitan         4019.0  
1      160.2564       51.0  Northern Metropolitan         4019.0

In [53]:
df2=df.copy().select_dtypes(exclude='object')
df2.head(3)

Rooms         Price  Distance  Bathroom  Car  Landsize  BuildingArea  \
0      2  1.050173e+06       2.5       1.0  1.0     126.0      160.2564   
1      2  1.480000e+06       2.5       1.0  1.0     202.0      160.2564   
2      2  1.035000e+06       2.5       1.0  0.0     156.0       79.0000   

   YearBuilt  Propertycount  
0       51.0         4019.0  
1       51.0         4019.0  
2      121.0         4019.0

In [54]:
x=df2.drop('Price',axis=1).values
y=df2['Price'].values

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

In [56]:
x.shape

(34857, 8)

In [57]:
x_train.shape

(26142, 8)

In [58]:
x_test.shape

(8715, 8)

In [59]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [60]:
y_pred=model.predict(x_test)
y_pred

array([ 861876.4003748 ,  434270.62870966,  935684.02800715, ...,
       1303958.21865704, 1051899.70926514,  708980.16378093])

In [61]:
y_test

array([ 857000.        , 1050173.34495541, 1000000.        , ...,
       1518000.        ,  760000.        ,  455000.        ])

In [63]:
from sklearn.metrics import r2_score
print("R2_score",r2_score(y_test,y_pred))

R2_score 0.22017037304473386


In [64]:
x_train[0]

array([1.000e+00, 4.300e+00, 1.000e+00, 1.000e+00, 8.870e+02, 4.500e+01,
       4.900e+01, 4.918e+03])

In [69]:
model.predict([[1, 4.300e+00, 1.000e+00, 1.000e+00, 8.870e+02, 4.500e+01,
       4.900e+01, 4.918e+03]])

array([647404.30795727])