In [3]:
print("hello")

hello


In [4]:
#Numpy
#Python
#Datatypes
#Lists, Tuples, Dictionary

In [5]:
print(4)

4


In [12]:
i=0  #starting point or initialization
while(i<5):   #condition or the ending point
    print(i)
    i=i+1    #increment/decrement or step
print("End of the loop")

0
1
2
3
4
End of the loop


In [13]:
for i in range(0,5,1):
    print(i)
print("End of the loop")

0
1
2
3
4
End of the loop


In [14]:
for i in range(2,15,3):
    print(i)
print("End of the loop")

2
5
8
11
14
End of the loop


In [15]:
for i in range(12,5,-3):
    print(i)
print("End of the loop")

12
9
6
End of the loop


In [16]:
abc=[2,5,7,8,4]

In [17]:
abc1=(2,4,3,5,3)

In [20]:
abc

[2, 5, 7, 8, 4]

In [21]:
abc[0]  #printing 0th element of the list

2

In [23]:
abc[2]

7

In [24]:
abc[1:5]

[5, 7, 8, 4]

In [25]:
abc[2:]

[7, 8, 4]

In [18]:
for i in abc:
    print(i)

2
5
7
8
4


In [19]:
for i in [2,5,7,8,4]:
    print(i)

2
5
7
8
4


In [28]:
import time
for i in range(0,5,1):
    print(i)
    time.sleep(1)
print("End of the loop")

0
1
2
3
4
End of the loop


In [31]:
import time as ti
for i in range(0,5,1):
    print(i)
    ti.sleep(1)
print("End of the loop")

0
1
2
3
4
End of the loop


In [35]:
from time import sleep
for i in range(0,5,1):
    print(i)
    sleep(0.5)
print("End of the loop")

0
1
2
3
4
End of the loop


In [36]:
from time import sleep as sl
for i in range(0,5,1):
    print(i)
    sl(0.5)
print("End of the loop")

0
1
2
3
4
End of the loop


In [38]:
#Numpy       - Numerical Calculations
#Pandas      - Data Analysis
#Matplotlib  - Data Visualization
#Seaborn, Plotly - Advanced Visualization libraries
#scikit learn - all the algorithms

In [39]:
#Numpy

In [41]:
import numpy as np

In [42]:
#creating a numpy array
arr1=np.array([2,4,6,5,3])

In [43]:
arr1

array([2, 4, 6, 5, 3])

In [44]:
abc

[2, 5, 7, 8, 4]

In [47]:
type(abc)

list

In [48]:
a=2
type(a)

int

In [45]:
type(arr1)

numpy.ndarray

In [46]:
len(arr1)

5

In [49]:
arr1[0]

2

In [50]:
arr1[-1]

3

In [51]:
arr1[1:4]

array([4, 6, 5])

In [52]:
#random method of numpy

In [60]:
np.random.seed(1)
a=np.random.randint(0,50,10)
a

array([37, 43, 12,  8,  9, 11,  5, 15,  0, 16])

In [74]:
#OTP generation

otp=np.random.randint(0,9,6)
otp

array([7, 7, 4, 0, 2, 0])

In [75]:
#create an array of 20 random numbers between 0 and 10

In [77]:
c=np.random.randint(0,10,20)
c

array([6, 6, 2, 7, 7, 0, 6, 5, 1, 4, 6, 0, 6, 5, 1, 2, 1, 5, 4, 0])

In [78]:
np.unique(c)

array([0, 1, 2, 4, 5, 6, 7])

In [79]:
np.sort(c)

array([0, 0, 0, 1, 1, 1, 2, 2, 4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7])

In [80]:
np.unique(c,return_counts=True)

(array([0, 1, 2, 4, 5, 6, 7]), array([3, 3, 2, 2, 3, 5, 2], dtype=int64))

In [81]:
d=np.unique(c)
d

array([0, 1, 2, 4, 5, 6, 7])

In [86]:
e=np.append(d,8)
e

array([0, 1, 2, 4, 5, 6, 7, 8])

In [89]:
f=np.power(e,2)
f

array([ 0,  1,  4, 16, 25, 36, 49, 64], dtype=int32)

In [91]:
g=np.sqrt(f)
g

array([0., 1., 2., 4., 5., 6., 7., 8.])

In [116]:
a1=np.array([1,3,2,5,4,6,7,6])
a1

array([1, 3, 2, 5, 4, 6, 7, 6])

In [93]:
len(a1)

8

In [94]:
a1.size

8

In [95]:
a1.ndim

1

In [96]:
a1.dtype

dtype('int32')

In [97]:
a1.shape

(8,)

In [111]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
b.size

8

In [101]:
b.ndim

2

In [102]:
b.shape

(2, 4)

In [108]:
c=b.reshape(4,2)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [109]:
c.shape

(4, 2)

In [114]:
a2=np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])
a2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [133]:
a2.ndim

2

In [115]:
a2.shape

(1, 12)

In [122]:
a2.size

12

In [124]:
a2.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [126]:
np.random.seed(1)
a=np.random.randint(0,50,10)
a

array([37, 43, 12,  8,  9, 11,  5, 15,  0, 16])

In [131]:
np.random.seed(1)
a=np.random.randint(0,50,(5,2))
a

array([[37, 43],
       [12,  8],
       [ 9, 11],
       [ 5, 15],
       [ 0, 16]])

In [134]:
#arange and linspace

In [135]:
a4=np.arange(2,18,3)
a4

array([ 2,  5,  8, 11, 14, 17])

In [136]:
np.arange(0,5,1)

array([0, 1, 2, 3, 4])

In [137]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [138]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [139]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [140]:
a4

array([ 2,  5,  8, 11, 14, 17])

In [142]:
a4.min()

2

In [143]:
a4.max()

17

In [145]:
a4.mean()

9.5

In [146]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [148]:
c.max()

8

In [149]:
a4.sum()

57

In [153]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [150]:
c.sum()

36

In [151]:
c.sum(axis=0)

array([16, 20])

In [155]:
c.sum(axis=1)

array([ 3,  7, 11, 15])

In [157]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [158]:
np.arange(0,9,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [159]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [160]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [161]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [166]:
a=np.arange(9,dtype=np.float16).reshape(3,3)
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float16)

In [167]:
b=np.array([10,9,8])

In [168]:
np.add(a,b)

array([[10., 10., 10.],
       [13., 13., 13.],
       [16., 16., 16.]])

In [169]:
np.subtract(a,b)

array([[-10.,  -8.,  -6.],
       [ -7.,  -5.,  -3.],
       [ -4.,  -2.,   0.]])

In [170]:
np.multiply(a,b)

array([[ 0.,  9., 16.],
       [30., 36., 40.],
       [60., 63., 64.]])